name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: build
      run: gcc maincodecc.c -0 maincodecc.exe
    - name: run
      run: .\maincodecc.exe
    - name: make distcheck
      run: make distcheck
